### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by IPSE-TEAM** [pocethereum/appdesktop.fe#1]
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting got@9.6.0:
npm ERR! Verification failed while extracting got@9.6.0:
npm ERR! sha1-7fRefWf5lUVwXeH3u+7rPocl7YU= integrity checksum failed when using sha1: wanted sha1-7fRefWf5lUVwXeH3u+7rPocl7YU= but got sha512-R7eWptXuGYxwijs0eV+v3o6+XH1IqVK8dJOEecQfTmkncw9AV4dcw/Dhxi8MdlqPthxxpZyizMzyg8RTmEsG+Q== sha1-7fRefWf5lUVwXeH3u+7rEhdl7YU=. (24649 bytes)
npm WARN tar ENOENT: no such file or directory, open '/Users/mac/gopath/src/github.com/pocethereum/appdesktop.fe/node_modules/.staging/accessibility-developer-tools-e7398c1b/lib/closure-library/closure/goog/result/result_interface.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/mac/gopath/src/github.com/pocethereum/appdesktop.fe/node_modules/.staging/accessibility-developer-tools-e7398c1b/lib/closure-library/closure/goog/result/chain_test.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/mac/gopath/src/github.com/pocethereum/appdesktop.fe/node_modules/.staging/accessibility-developer-tools-e7398c1b/lib/closure-library/closure/goog/result/simpleresult.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/mac/gopath/src/github.com/pocethereum/appdesktop.fe/node_modules/.staging/accessibility-developer-tools-e7398c1b/lib/closure-library/closure/goog/result/resultutil_test.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/mac/gopath/src/github.com/pocethereum/appdesktop.fe/node_modules/.staging/accessibility-developer-tools-e7398c1b/lib/closure-library/closure/goog/result/deferredadaptor_test.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/mac/gopath/src/github.com/pocethereum/appdesktop.fe/node_modules/.staging/accessibility-developer-tools-e7398c1b/lib/closure-library/closure/goog/result/resultutil.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/mac/gopath/src/github.com/pocethereum/appdesktop.fe/node_modules/.staging/accessibility-developer-tools-e7398c1b/lib/closure-library/closure/goog/result/resultutil_test.html'
npm WARN tar ENOENT: no such file or directory, open '/Users/mac/gopath/src/github.com/pocethereum/appdesktop.fe/node_modules/.staging/accessibility-developer-tools-e7398c1b/lib/closure-library/closure/goog/result/simpleresult_test.html'
npm WARN tar ENOENT: no such file or directory, open '/Users/mac/gopath/src/github.com/pocethereum/appdesktop.fe/node_modules/.staging/accessibility-developer-tools-e7398c1b/lib/closure-library/closure/goog/result/deferredadaptor_test.html'
npm WARN tar ENOENT: no such file or directory, open '/Users/mac/gopath/src/github.com/pocethereum/appdesktop.fe/node_modules/.staging/accessibility-developer-tools-e7398c1b/lib/closure-library/closure/goog/result/transform_test.html'
npm WARN tar ENOENT: no such file or directory, open '/Users/mac/gopath/src/github.com/pocethereum/appdesktop.fe/node_modules/.staging/accessibility-developer-tools-e7398c1b/lib/closure-library/closure/goog/result/combine_test.html'
npm WARN tar ENOENT: no such file or directory, open '/Users/mac/gopath/src/github.com/pocethereum/appdesktop.fe/node_modules/.staging/accessibility-developer-tools-e7398c1b/lib/closure-library/closure/goog/result/wait_test.html'
npm WARN tar ENOENT: no such file or directory, open '/Users/mac/gopath/src/github.com/pocethereum/appdesktop.fe/node_modules/.staging/accessibility-developer-tools-e7398c1b/lib/closure-library/closure/goog/result/chain_test.html'
npm WARN tar ENOENT: no such file or directory, open '/Users/mac/gopath/src/github.com/pocethereum/appdesktop.fe/node_modules/.staging/less-0fdaa408/dist/less.min.js'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2019-12-13T02_52_00_252Z-debug.log
(base) macdeMacBook-Pro:appdesktop.fe mac$ vim src/Common.js
(base) macdeMacBook-Pro:appdesktop.fe mac$ npm install
npm WARN tarball tarball data for got@9.6.0 (sha1-7fRefWf5lUVwXeH3u+7rPocl7YU=) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for got@9.6.0 (sha1-7fRefWf5lUVwXeH3u+7rPocl7YU=) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, open '/Users/mac/gopath/src/github.com/pocethereum/appdesktop.fe/node_modules/.staging/underscore-cd76c4e7/underscore.js'
npm WARN tar ENOENT: no such file or directory, open '/Users/mac/gopath/src/github.com/pocethereum/appdesktop.fe/node_modules/.staging/underscore-40b9dcd9/underscore.js'
npm WARN com.poc.desktop@1.0.0 No repository field.
npm WARN com.poc.desktop@1.0.0 No license field.

npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting got@9.6.0:
npm ERR! Verification failed while extracting got@9.6.0:

**Comment by pocethereum** [comment]
Please remove the package-lock.json, and run "npm install" again.
Similar to https://github.com/eshengsky/iBlog2/issues/52

**Comment by xera-2011** [comment]
我删掉了package-lock.json再npm install 就出现了下面的情况
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated babel-preset-babili@0.1.4: babili has been renamed to babel-minify. Please update to babel-preset-minify
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated webdriverio@4.14.4: outdated version, please use @next
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hawk@3.1.3: This version has been deprecated. Please upgrade to the latest version to get the best features, bug fixes, and security patches.
npm WARN deprecated @types/bignumber.js@5.0.0: This is a stub types definition for bignumber.js (https://github.com/MikeMcl/bignumber.js/). bignumber.js provides its own type definitions, so you don't need @types/bignumber.js installed!
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated uws@9.14.0: New code is available at github.com/uNetworking/uWebSockets.js
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/ubbey/node-upnp-utils.git
npm ERR!
npm ERR! fatal: unable to access 'https://github.com/ubbey/node-upnp-utils.git/': Could not resolve host: github.com
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\**\AppData\Roaming\npm-cache\_logs\2020-01-02T11_13_57_940Z-debug.log
